name: Chewer Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-windows:
    runs-on: windows-latest

    env:
      ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM development package
        shell: pwsh
        run: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/clang+llvm-21.1.8-x86_64-pc-windows-msvc.tar.xz"

          Invoke-WebRequest `
            -Uri $url `
            -OutFile "$env:RUNNER_TEMP\llvm.tar.xz"

          New-Item -ItemType Directory -Force -Path "C:\LLVM" | Out-Null

          tar -xf "$env:RUNNER_TEMP\llvm.tar.xz" `
            -C "C:\LLVM" `
            --strip-components=1

          Add-Content $env:GITHUB_PATH "C:\LLVM\bin"

          Write-Host "LLVM installed:"
          clang --version
          lld-link --version

          Write-Host "`nLLVMConfig.cmake:"
          Get-ChildItem "C:\LLVM" -Recurse -Filter "LLVMConfig.cmake" |
            Select-Object -ExpandProperty FullName
      - name: Find LLVM CMake config
        shell: pwsh
        run: |
          $config = Get-ChildItem "C:\Program Files\LLVM" `
            -Recurse `
            -Filter "LLVMConfig.cmake" `
            -ErrorAction SilentlyContinue |
            Select-Object -First 1

          if (-not $config) {
              throw "LLVMConfig.cmake was not found!"
          }

          Write-Host "LLVMConfig.cmake found at:"
          Write-Host $config.FullName

          Write-Host "LLVM_DIR:"
          Write-Host $config.DirectoryName
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Check MSVC
        shell: pwsh
        run: |
          cl
      
      - name: Build Chewer
        shell: pwsh
        run: |
          $env:LLVM_DIR = "C:\Program Files\LLVM\lib\cmake\llvm"

      - name: Build Chewer
        shell: pwsh
        run: |
          cmake --preset ninja-debug

      - name: Inspect zlib
        shell: pwsh
        run: |
          Write-Host "=== zlib install directory ==="
          Get-ChildItem "$env:ROOT\build\zlib-install" -Recurse |
            Select-Object FullName

      - name: Build Chewer
        shell: pwsh
        run: |
          cmake --build --preset ninja-debug
      
      - name: Test Chewer
        shell: pwsh
        run: |
          cd build

          .\bitec.exe "$env:ROOT\examples\bit.bite" -o "$env:ROOT\build\bit.obj" windows

          $output = "3" | .\bit.exe

          Write-Host "Program returned: $output"

          if ($output.Trim() -ne "3") {
              throw "Expected 3, got $output"
          }

  test-linux:
    runs-on: windows-latest

    env:
      ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Chewer
        shell: pwsh
        run: |
          cmake --preset ninja-debug

      - name: Inspect zlib
        shell: pwsh
        run: |
          Write-Host "=== zlib install directory ==="
          Get-ChildItem "$env:ROOT\build\zlib-install" -Recurse |
            Select-Object FullName

      - name: Build Chewer
        shell: pwsh
        run: |
          cmake --build --preset ninja-debug

      - name: Test Linux Target
        shell: pwsh
        run: |
          cd build

          .\bitec.exe "$env:ROOT\examples\bit.bite" -o "$env:ROOT\build\bit.o" linux64

          $linuxPath = wsl wslpath -a "$env:ROOT/build/bit"

          Write-Host "Linux executable: $linuxPath"

          $output = wsl bash -c "echo 3 | '$linuxPath'"

          Write-Host "Program returned: $output"

          if ($output.Trim() -ne "3") {
              throw "Expected 3, got $output"
          }